name: Contribs
on:
  pull_request_target:
    types: [opened, reopened]
#schedule:
#    - cron:  '*/15 * * * *'
#  pull_request_target:
#    types:
#      - closed
#      - labeled

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Contribs
    steps:
      - name: Contribs
        uses: carlescufi/action-contribs@main
        with:
          github-token: ${{ secrets.NCS_GITHUB_TOKEN }}
          command: 'external'
          messages: 'test message\nnew line | second message\nanother line'
          labels: 'test label 1, test label 2'
