name: Contribs
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Contribs
    steps:
      - name: Contribs
        uses: carlescufi/action-contribs@main
        with:
          github-token: ${{ secrets.NCS_GITHUB_TOKEN }}
          command: 'external'
          messages: |
                    Thank you your contribution!
                    It seems you are not a member of the nrfconnect GitHub organization.
                    We are currently not accepting external contributions, but this may change soon.
                    Please use https://devzone.nordicsemi.com/ for further information.
                    |
                    The author of this Pull Request is now a member of the nrfconnect GitHub organization.
          labels: 'external'
