name: Manifest
on:
  - pull_request_target

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Manifest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          fetch-depth: 0

      - name: Manifest
        uses: carlescufi/action-manifest@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          manifest-path: 'west.yml'
          checkout-path: 'ncs/nrf'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest, west'
          dnm-labels: 'DNM'
