name: Manifest
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Manifest
    steps:
      - name: Manifest
        uses: carlescufi/action-manifest@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          manifest-path: 'west.yml'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          messages: |
                    Test message for the manifest.
          labels: 'manifest, west'
          dnm-labels: 'DNM'
